### ISSUE TITLE
SensorsManager.getSensors: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by trzimar** [profesorfalken/jSensors#2]
> java.lang.ArrayIndexOutOfBoundsException: 1
	at com.profesorfalken.jsensors.manager.SensorsManager.getSensors(SensorsManager.java:100)
	at com.profesorfalken.jsensors.manager.SensorsManager.getCpu(SensorsManager.java:66)
	at com.profesorfalken.jsensors.manager.SensorsManager.getComponents(SensorsManager.java:54)
	at com.profesorfalken.jsensors.SensorsLocator.getComponents(SensorsLocator.java:34)
	at com.profesorfalken.jsensors.JSensors.components(JSensors.java:73)
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureByjSensors(TemperatureUtils.java:41)
	at org.jutils.jhardware.util.TemperatureUtils.getCpuTemperatureForWindows(TemperatureUtils.java:59)
	at org.jutils.jhardware.info.processor.windows.WindowsProcessorInfo.parseInfo(WindowsProcessorInfo.java:54)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:29)
	at org.jutils.jhardware.info.processor.AbstractProcessorInfo.getInfo(AbstractProcessorInfo.java:25)
	at org.jutils.jhardware.HardwareInfo.getProcessorInfo(HardwareInfo.java:52)

**Comment by profesorfalken** [comment]
Hello, 

Could you execute JSensors in debug mode?

    Map<String, String> overriddenConfig = new HashMap<String, String>();
    overriddenConfig.put("debugMode", "true");

    [...]
    Components components = JSensors.get.config(overriddenConfig).components();

And post here the output?

What is your system? How are you trying to integrate jSensors?

Thanks

**Comment by trzimar** [comment]
Hi,

well, debug output is:
> 
INFO  c.p.j.m.w.WindowsSensorsManager - RawSensorData: 
INFO  c.p.j.m.w.WindowsSensorsManager - NormalizeSensorData: 

System is Citrix Windows Server 2008 R2 and we simply call:
`org.jutils.jhardware.HardwareInfo.getProcessorInfo();`

Could temperature information be excluded from getting CPU info?

Windows PowerShell also stops working (exception in clr.dll modul) when calling this, but it is windows thing...

Thanks!

**Comment by profesorfalken** [comment]
Hello,

OK I understand now. You are using jHardware and not directly jSensors.
Yes, in a citrix machine, the cpu temperature has no sense. I will try to control better the case when no data is retrieved.

I will keep you updated.

**Comment by profesorfalken** [comment]
Hello,

Should be fixed if you use jHardware v0.8.3

Best regards

**Comment by trzimar** [comment]
Hello,

it is fixed, thanks!

Regards.
